#!/usr/bin/env bash
#
# Google search text from the x11 primary clipboard
#
###

clip=$(xclip -o)
gs=$(echo -ne "$clip" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
firefox http://www.google.com/search?q="$gs"
