#!/usr/bin/env sh
#
# if there is visible stuff in the directory, just run ls
# if there is no visible stuff, run ls -a
# takes either no arguments, or one directory to ls on
# if more arguments are used then just call ls
#
###

com='ls --color=auto -1 --group-directories-first'

if [[ $# > 1 || $1 == -* || $(ls -1 $* | wc -l) > 0 ]]; then
  exec $com $*
else
  exec $com -a $*
fi
