#!/bin/bash
#
# Make and edit a new plain text file in the notes directory
#
# note [OPTION] ... [FILE]
#
#   -l to list all notes
#   -d to append the date to the note name
#   -t to append unix epoch time as a unique timestamp to the note name
#
#   file defaults to "note" if left blank
#
###

DIR=~/Documents/notes/
name=note
date=''
stamp=''

for arg in "$@"
do
  case "$arg" in
    "-l" ) ls -1 $DIR; exit 0
      ;;
    "-d" ) date=_$(date +%Y_%m_%d)
      ;;
    "-t" ) stamp=_$(date +%s)
      ;;
    * )    if [[ "$name" == note ]]; then name=$arg; fi
  esac
done

# if all defaults are still on, then force a date
if [[ "$name" == note && "$date" == "" && "$stamp" == "" ]]; then
  date=_$(date +%Y_%m_%d)
fi

$EDITOR ${DIR}${name}${date}${stamp}

exit 0
